name = "Hammer"
author = "UltraStorm"
version = "1.4.0+1.19.4.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1602fd84716af08ae5cd1a9b3c6f2e9a79d1be417092f50b612dedb68345c9b7"

[versions]
forge = "45.0.66"
minecraft = "1.19.4"
