name = "Hammer"
author = "intergrav and WaffleIBOT"
version = "1.5+1.19.4.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12434abf70a5448885955ff0190b370c88fe302c038810fa4f977e3b131f7b7f"

[versions]
forge = "45.2.0"
minecraft = "1.19.4"
