name = "Hammer"
author = "intergrav and WaffleIBOT"
version = "1.5.4+1.19.4.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2260fab9f05e31464ccb9cf7a715a767b6d499640db4096ef0d06a8476dfd32c"

[versions]
forge = "45.2.0"
minecraft = "1.19.4"
