name = "Hammer"
author = "WaffleIBOT"
version = "1.5.7+1.20.1.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "775fc844bd36af02b0cefa4192778d0839fc2b04d2004a27ba21f76d3cba0bbf"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
