name = "Hammer"
author = "UltraStorm"
version = "1.4.0+1.18.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "300bb806d8a16b358a1316d3a40c5a10d539c00a8e3fecc953480d6f720493bc"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
