name = "Hammer"
author = "intergrav and WaffleIBOT"
version = "1.5.9+1.18.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b056af7b196dea9922ba172dfdbb9ce54dcff547e98ddb8397e26bb7bfc612e"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
