name = "Hammer"
author = "intergrav and WaffleIBOT"
version = "1.5.6+1.18.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6555e1768e70d78893f82390730548266375e959f17db8da087b51111f41fbb2"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
