name = "Hammer"
author = "UltraStorm"
version = "1.3.0+1.18.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8c7fa6a7fc8aeb39a15f816413c4f8b6cd418fef79fc795ae1826166dcd2d42"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
