name = "Hammer"
author = "intergrav and WaffleIBOT"
version = "1.5.8+1.18.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66089264d547f1ddc82d3302c88bf542a77f128df3d960daa81128713f5b7986"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
