name = "Hammer"
author = "intergrav and WaffleIBOT"
version = "1.6.0+1.18.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55bdcfc3758db468b90c56281ed8db24b84cc381be2150a97372900948ccbd94"

[versions]
forge = "40.2.18"
minecraft = "1.18.2"
