name = "Hammer"
version = "1.6.4+1.21.0.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d23ea338b29125f7089a5a28e701e070bbb619aad2ef5b797acc974cffb8d1a7"

[versions]
minecraft = "1.21"
neoforge = "21.0.21-beta"
