name = "Hammer"
version = "1.7.1+1.21.0.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2065d74bc8f9abf850ad02caf698e209a11b2b927bbe93e3a43aabc4dca548ef"

[versions]
minecraft = "1.21"
neoforge = "21.0.87-beta"
