name = "Hammer"
author = "UltraStorm"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "242c468e33915612f8c156c2e8a8b9d4ff4f9a89e99a5a3e04384903646b0c70"

[versions]
forge = "43.0.8"
minecraft = "1.19.2"
