name = "Hammer"
author = "intergrav and WaffleIBOT"
version = "1.5.9+1.19.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "440d5addcd39bab26167492721b5901eabacb2e19068509777e497abf0596dc7"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
