name = "Hammer"
author = "intergrav and WaffleIBOT"
version = "1.5.9+1.19.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7cb574afc6ea8b5b6a8ae0d976e504558448225344174cce433db77917967c93"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
