name = "Hammer"
author = "intergrav and WaffleIBOT"
version = "1.6.2+1.19.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1dcbf763728595993ed6bf49c355a4032901c54085b31944b37e6d3cb3a5a8a4"

[versions]
forge = "43.3.13"
minecraft = "1.19.2"
