name = "Hammer"
author = "intergrav and WaffleIBOT"
version = "1.6.1+1.19.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12d3e37f214524392206bba26c39a9414bdae17e22665f8d571fd530f8643892"

[versions]
forge = "43.3.13"
minecraft = "1.19.2"
