name = "Hammer"
author = "intergrav and WaffleIBOT"
version = "1.5.5+1.19.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "346674d6c274344725be1abe0a4735d0e84d9bd46078964c809af36adfe880ee"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
