name = "Hammer"
author = "UltraStorm"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ed588a2a6554cfa9f2a7fc5da7fa677c96f8767c78819c22484e45abd8b3eed"

[versions]
forge = "42.0.9"
minecraft = "1.19.1"
