name = "Hammer"
author = "WaffleIBOT"
version = "1.7.1+1.20.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b89cc96691fea4377ffbb9f3f480689109430219fc4934f1f21ea05dd26f830"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
