name = "Hammer"
author = "WaffleIBOT"
version = "1.8.3+1.20.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b20fe75ed4c41c3b47be027588e03c1c262dd8b0790ab8046e101acc98470e1"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
