name = "Hammer"
author = "WaffleIBOT"
version = "1.7.3+1.20.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bba5c56d9e41d5181ebb09c22cbae3f0cc18c97261edecb1c11487017c1857b"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
