name = "Hammer"
author = "WaffleIBOT"
version = "1.7.0+1.20.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "feaa109e26c6ce178812db4016f0bad051c6c24d90806d6a5846278fdcfc9217"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
