name = "Hammer"
version = "1.6.4+1.20.6.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c71d68e42ab2fdd3e37a315b726f2bcbf5ddd036e31ab995ed14c7005b3c068"

[versions]
minecraft = "1.20.6"
neoforge = "20.6.116"
