name = "Hammer"
version = "1.7.0+1.20.6.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34c93d450ea87a5da5d4ff3c5faa9d212b63305bec6a6d4dd6d76445a41eb0f6"

[versions]
minecraft = "1.20.6"
neoforge = "20.6.119"
