name = "Hammer"
version = "1.6.2+1.20.6.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6caf9e1a6b8ee735839ed072b9e56b48fd2e2f47b482fbe9d301218d27556eef"

[versions]
minecraft = "1.20.6"
neoforge = "20.6.100-beta"
