name = "Hammer"
author = "UltraStorm"
version = "1.2.0+1.19.3.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "719e8e442f894f59468af882ff118d0421e276726171a0c24a3811e5b855cd8a"

[versions]
forge = "44.1.0"
minecraft = "1.19.3"
