name = "Hammer"
version = "1.6.0+1.20.4.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d11a3152b114eaad136dbafae80cb5a2b9e288934791e64fadf8630e0545ebab"

[versions]
minecraft = "1.20.4"
neoforge = "20.4.225"
