name = "Hammer"
version = "1.6.4+1.20.4.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fbf166634e9270c651bae2f21d015c33ff57c554af6b355b5f0a1bb3d2988ac"

[versions]
minecraft = "1.20.4"
neoforge = "20.4.237"
