name = "Hammer"
version = "1.7.0+1.20.4.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee0619be59cafd24084a38c46c9499646c6779eb9ca99a84cbf6813056926da6"

[versions]
minecraft = "1.20.4"
neoforge = "20.4.237"
