name = "Hammer"
version = "1.6.4+1.20.4.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b218f755b3c1828003ef65a92cc3508c6c7ef380f35dc9dfeccc05d673dc2b0"

[versions]
minecraft = "1.20.4"
neoforge = "20.4.237"
