name = "Hammer"
version = "1.6.3+1.20.4.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edbb73178015edc5caa7d0a05d7c3200ad32a045ef772a2b2cd9b4db66384ae6"

[versions]
minecraft = "1.20.4"
neoforge = "20.4.237"
