name = "Hammer"
author = "WaffleIBOT"
version = "1.8.3+1.20.4.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c084c7cf230ddacbdaadc4161c704f6857a7e0164306523c2dc1270596c0944a"

[versions]
minecraft = "1.20.4"
neoforge = "20.4.237"
